name: Validacion Completa del Proyecto

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

  
      - name: Verificar index.html
        run: test -f frontend/index.html

      - name: Verificar login.html
        run: test -f frontend/login.html

      - name: Verificar registrar.html
        run: test -f frontend/registrar.html

      - name: Verificar panel principal
        run: test -f frontend/paginas/panel-principal.html

      - name: Verificar servidor de Node.js
        run: test -f backend/server.js

      - name: Verificar archivo de configuración package.json
        run: test -f backend/package.json